import os
import io
import pandas as pd
from flask import Flask, request, send_file, jsonify
from flask_cors import CORS
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib import colors
from datetime import datetime

app = Flask(__name__)
CORS(app)

API_URL = "https://script.google.com/macros/s/AKfycbz8JBmEGJGqKuz3rEZfkPQsyndPaVcAN4K-zmJUaTdk5l4WFvgNyHLfEWML2chY9J3g9w/exec"

def fetch_data():
    import urllib.request
    import json
    try:
        # Load JSON from Apps Script
        req = urllib.request.Request(API_URL)
        with urllib.request.urlopen(req) as response:
            data = json.loads(response.read().decode())
        df = pd.DataFrame(data)
        
        # Ensure column names match expectations (Map 'name' -> 'Name')
        df.rename(columns={'name': 'Name', 'date': 'Date', 'event': 'Event'}, inplace=True)
        return df
    except Exception as e:
        print(f"Error fetching data: {e}")
        return pd.DataFrame()

def filter_data(df, payload):
    if df.empty:
        return df
        
    filter_type = payload.get("filter")
    
    # Standardize column names just in case (assume Name, Date, Event)
    df.columns = df.columns.str.strip().str.title()
    
    if "Date" not in df.columns:
        # Depending on how the sheet is formatted, maybe it's called something else?
        # Assuming the standard Names: Name, Date, Event
        pass
        
    if filter_type == "date":
        target_date = payload.get("date")
        return df[df['Date'] == target_date]
        
    elif filter_type == "name":
        name = payload.get("name", "").lower()
        from_str = payload.get("from")
        to_str = payload.get("to")
        
        # Filter by name (case-insensitive substring match)
        mask_name = df['Name'].astype(str).str.lower().str.contains(name, na=False)
        
        try:
            from_dt = datetime.strptime(from_str, "%d-%m-%Y")
            to_dt = datetime.strptime(to_str, "%d-%m-%Y")
            
            # Need to parse sheet dates carefully. They should be in DD-MM-YYYY or similar.
            def is_in_range(d_str):
                try:
                    d_obj = datetime.strptime(str(d_str).strip(), "%d-%m-%Y")
                    return from_dt <= d_obj <= to_dt
                except:
                    return False
            
            mask_date = df['Date'].apply(is_in_range)
            return df[mask_name & mask_date]
        except Exception as e:
            print(f"Error parsing date range: {e}")
            return pd.DataFrame() # Return empty on error
            
    elif filter_type == "monthly":
        month = payload.get("month")   # e.g. "April"
        year = payload.get("year")     # e.g. "2026"
        
        def is_in_month(d_str):
            try:
                d_obj = datetime.strptime(str(d_str).strip(), "%d-%m-%Y")
                return d_obj.strftime("%B") == month and str(d_obj.year) == year
            except:
                return False
                
        return df[df['Date'].apply(is_in_month)]
        
    return pd.DataFrame()

def add_footer(canvas, doc):
    canvas.saveState()
    
    # Adding generated text
    now_str = datetime.now().strftime("%d-%m-%Y %I:%M %p")
    
    # Draw logo if exists
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    logo_path = os.path.join(project_root, "logo.png")
    
    draw_x = 0.5 * inch
    draw_y = 0.5 * inch
    
    canvas.setFont('Helvetica', 9)
    # 1. "Generated by "
    canvas.drawString(draw_x, draw_y, "Generated by ")
    draw_x += canvas.stringWidth("Generated by ", 'Helvetica', 9) + 2
    
    if os.path.exists(logo_path):
        try:
            # We draw it super small in the footer
            canvas.drawImage(logo_path, draw_x, draw_y - 0.1*inch, width=0.3*inch, height=0.3*inch, preserveAspectRatio=True, mask='auto')
            draw_x += 0.3 * inch + 4
        except Exception as e:
            pass
            
    # 2. "@ time"
    canvas.drawString(draw_x, draw_y, f" @ {now_str}")
    
    canvas.restoreState()

def build_pdf(df, payload):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
    elements = []
    
    styles = getSampleStyleSheet()
    
    # 1. Header
    title_style = ParagraphStyle(
        name="Header",
        parent=styles['Title'],
        fontName='Helvetica-Bold',
        fontSize=18,
        alignment=TA_CENTER,
        spaceAfter=20
    )
    
    filter_type = payload.get("filter")
    if filter_type == "date":
        title_text = f"OD REPORT FOR {payload.get('date')}"
    elif filter_type == "name":
        title_text = f"OD REPORT FOR {payload.get('name')} ({payload.get('from')} to {payload.get('to')})"
    elif filter_type == "monthly":
        title_text = f"OD REPORT FOR {payload.get('month')} {payload.get('year')}"
    else:
        title_text = "OD REPORT"
        
    elements.append(Paragraph(title_text, title_style))
    
    # 2. Table / Empty State
    if df.empty:
        empty_style = ParagraphStyle(
            name="Empty",
            parent=styles['Normal'],
            alignment=TA_CENTER,
            fontSize=12
        )
        elements.append(Spacer(1, 1*inch))
        elements.append(Paragraph("No data found for the selected filter.", empty_style))
    else:
        # Table Columns: Name | Date | Event
        headers = ["Name", "Date", "Event"]
        data = [headers]
        
        for _, row in df.iterrows():
            # If Event is long, wrap it in a Paragraph
            event_para = Paragraph(str(row.get('Event', '')), styles['Normal'])
            data.append([
                str(row.get('Name', '')), 
                str(row.get('Date', '')), 
                event_para
            ])
            
        t = Table(data, colWidths=[2*inch, 1.5*inch, 3*inch])
        
        # Style
        # Borders on all cells, center-aligned, adequate padding (6pt), alternating row shading
        table_style_commands = [
            ('BOX', (0,0), (-1,-1), 1, colors.black),
            ('GRID', (0,0), (-1,-1), 1, colors.black),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('TOPPADDING', (0,0), (-1,-1), 6),
        ]
        
        # Alternating Row Shading
        for i in range(1, len(data)):
            if i % 2 == 0:
                table_style_commands.append(('BACKGROUND', (0,i), (-1,i), colors.lightgrey))
                
        t.setStyle(TableStyle(table_style_commands))
        elements.append(t)
        
        # 3. Footer summary
        elements.append(Spacer(1, 0.2*inch))
        
        summary_style = ParagraphStyle(
            name="Summary",
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            alignment=TA_RIGHT,
            fontSize=12
        )
        records_count = len(df)
        elements.append(Paragraph(f"Total ODs: {records_count}", summary_style))
        
    # Build without the default template, inject footer
    doc.build(elements, onFirstPage=add_footer, onLaterPages=add_footer)
    
    buffer.seek(0)
    return buffer

@app.route('/generate-pdf', methods=['POST'])
def generate_pdf():
    try:
        payload = request.get_json()
        if not payload:
            return jsonify({"error": "Invalid JSON"}), 400
            
        df = fetch_data()
        filtered_df = filter_data(df, payload)
        
        pdf_buffer = build_pdf(filtered_df, payload)
        
        filter_type = payload.get("filter", "report")
        filename = f"OD_Report_{filter_type}.pdf"
        
        return send_file(
            pdf_buffer,
            as_attachment=True,
            download_name=filename,
            mimetype='application/pdf'
        )
    except Exception as e:
        print(f"Server error: {e}")
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port, debug=True)
